### ISSUE TITLE
Keep comments while dereferencing spec?

### ISSUE THREAD

**Issue by bmoyroud** [readmeio/oas-normalize#247]
Hey team - thanks for your work!

Is it possible to keep comments in spec while dereferencing an API definition?
Hoping I could do something like

```
const oas = new OASNormalize(filePath, { enablePaths: true, keepComments: true }); 
const definition = await oas.deref();
```

**Comment by erunion** [comment]
Curious, but what do you mean by comments? There's no sort of comment  system within OpenAPI. You referring to YAML comments?

**Comment by bmoyroud** [comment]
@erunion - yes YAML comments :)

**Comment by erunion** [comment]
Unfortunately we can't do this because [@apidevtools/swagger-parser](https://npm.im/@apidevtools/swagger-parser), which we use (or rather a fork of) to validate OpenAPI definitions, returns by default a JSON object and in order to do that when it parses YAML with [js-yaml](https://npm.im/js-yaml) it only returns what can be put into a JSON object.

But even if that did support returning a YAML object, and retain comments, the dereferencing process in [@apidevtools/json-schema-ref-parser](https://npm.im/@apidevtools/json-schema-ref-parser) would need to be completely rewritten to have awareness of YAML comments as it also currently mainly returns JSON objects.

However If you really want to retain comments you can probably do so by converting you definition to JSON and then changing your comments to be embedded within an `x-comment` extension as all these libraries will retain that, and it'll be ignored by OpenAPI validation.

**Comment by bmoyroud** [comment]
@erunion - thanks for your quick response. Yup I dug into your dependencies over last few days to solve another issue (some $ref paths erroring) and realized this would be tricky to implement. I like your idea of extension - thanks for suggesting!
